/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AnalysisParameters;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-08-11T15:52:03.807Z[GMT]")
@Api(value = "analyze", description = "the analyze API")
public interface AnalyzeApi {

	@ApiOperation(value = "generates an activity analysis", nickname = "analyzePost", notes = "", tags = {
			"developers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "analysis generated successfully"),
			@ApiResponse(code = 400, message = "invalid set of parameters") })
	@RequestMapping(value = "/analyze", consumes = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<Void> analyzePost(
			@ApiParam(value = "parameters used for activity analysis") @Valid @RequestBody AnalysisParameters body);

}
