/**
* Activity Tracker API
* Activity Tracker API for Brandeis Boys
*
* The version of the OpenAPI document: 1.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import com.squareup.moshi.Json
/**
 *
 * @param date
 * @param activityType
 * @param duration
 * @param repetitions
 */

data class ActivityBase(
    @Json(name = "date")
    val date: kotlin.String,
    @Json(name = "activityType")
    val activityType: ActivityType,
    @Json(name = "duration")
    val duration: ActivityDuration,
    @Json(name = "repetitions")
    val repetitions: kotlin.Int
)
