/**
* Activity Tracker API
* Activity Tracker API for Brandeis Boys
*
* The version of the OpenAPI document: 1.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import com.squareup.moshi.Json
/**
 *
 * @param userId
 * @param activityType
 * @param timespan
 */

data class AnalysisParameters(
    @Json(name = "userId")
    val userId: kotlin.String,
    @Json(name = "activityType")
    val activityType: ActivityType,
    @Json(name = "timespan")
    val timespan: Timespan
)
