/**
* Activity Tracker API
* Activity Tracker API for Brandeis Boys
*
* The version of the OpenAPI document: 1.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import com.squareup.moshi.Json

/**
*
* Values: days,weeks,months,years
*/

enum class TimespanUnits(val value: kotlin.String) {

    @Json(name = "days")
    days("days"),

    @Json(name = "weeks")
    weeks("weeks"),

    @Json(name = "months")
    months("months"),

    @Json(name = "years")
    years("years");

    /**
     This override toString avoids using the enum var name and uses the actual api value instead.
     In cases the var name and value are different, the client would send incorrect enums to the server.
     **/
    override fun toString(): String {
        return value
    }
}
